(() => {
  const $ = (selector) => document.querySelector(selector);
  const canvas = $("#biologyCanvas");
  const context = canvas.getContext("2d");
  const chart = $("#bioChart");
  const chartContext = chart.getContext("2d");
  const definitions = [
    ["photosynthesis", "Photosynthese", "Agrarwissenschaft", "Lichtenergie wird in Glucose gespeichert. Kohlenstoffdioxid und Wasser werden zu Zucker und Sauerstoff.", "Wie verändert stärkeres Licht die Sauerstoffproduktion?", [["licht", "Lichtstärke", 0, 100, 55, "%"], ["co2", "CO₂-Konzentration", 100, 1500, 420, "ppm"], ["temperatur", "Temperatur", 5, 45, 22, "°C"]]],
    ["enzymes", "Enzymaktivität", "Biochemie", "Enzyme beschleunigen Reaktionen. Temperatur und pH-Wert verändern ihre räumliche Struktur und Aktivität.", "Bei welcher Temperatur ist die Aktivität am größten?", [["temperatur", "Temperatur", 0, 80, 25, "°C"], ["ph", "pH-Wert", 2, 12, 7, ""], ["substrat", "Substrat", .1, 3, 1, "mmol/L"]]],
    ["osmosis", "Osmose", "Biophysik", "Wasser wandert durch eine semipermeable Membran zur höher konzentrierten Lösung.", "Was geschieht bei einer stark konzentrierten Außenlösung?", [["innen", "Zellkonzentration", .05, 2, .4, "mol/L"], ["aussen", "Außenkonzentration", .05, 2, .8, "mol/L"], ["volumen", "Startvolumen", 20, 100, 55, "%"]]],
    ["radiation", "Strahlenwirkung auf Zellgewebe", "Biophysik", "Virtuelles Modell: Ionisierende Strahlung kann DNA in Zellen schädigen. Abschirmung und Abstand verändern die Dosis im Gewebe.", "Wie verringern Abschirmung und Abstand die geschädigte Zellzahl?", [["dosis", "Strahlungsstärke", .1, 8, 2, "Gy/h"], ["abstand", "Abstand zur Quelle", 10, 150, 60, "cm"], ["abschirmung", "Abschirmung", 0, 10, 3, "cm"]]],
    ["respiration", "Zellatmung", "Biochemie", "Zellen gewinnen mit Sauerstoff Energie aus Glucose. Dabei entstehen Kohlenstoffdioxid, Wasser und ATP.", "Wie wirkt mehr Sauerstoff auf die ATP-Produktion?", [["glucose", "Glucose", .1, 5, 1.5, "mmol/L"], ["sauerstoff", "Sauerstoff", 1, 21, 12, "%"], ["temperatur", "Temperatur", 5, 42, 25, "°C"]]],
    ["population", "Populationswachstum", "Umweltwissenschaften", "Eine Population wächst zunächst schnell, wird aber durch begrenzte Nahrung und Raum an die Umweltkapazität gebunden.", "Wie verändert eine höhere Umweltkapazität das Wachstum?", [["start", "Startpopulation", 5, 200, 25, ""], ["kapazitaet", "Umweltkapazität", 100, 2000, 800, ""], ["rate", "Wachstumsrate", .05, 1, .35, "pro Tag"]]],
  ];
  const experiments = Object.fromEntries(definitions.map(([id, title, category, description, challenge, controls]) => [id, { id, title, category, description, challenge, controls }]));
  const explanations = {
    photosynthesis: "Chlorophyll nimmt Licht auf. Die Lichtreaktion liefert Energie, mit der CO₂ im Calvin-Zyklus zu Glucose gebunden wird. Sauerstoff entsteht aus Wasser.",
    enzymes: "Das aktive Zentrum bindet passende Substrate. Zu hohe Temperatur oder ein ungeeigneter pH-Wert verändert die Enzymstruktur, daher sinkt die Reaktionsrate.",
    osmosis: "Die Zellmembran lässt Wasser passieren, gelöste Teilchen jedoch kaum. Wasser bewegt sich zur Seite mit höherer Teilchenkonzentration, bis der osmotische Druck ausgeglichen ist.",
    radiation: "Dieses virtuelle Modell ist kein Test an Menschen. Es zeigt eine Gewebeprobe aus Zellen: Ionisierende Strahlung kann DNA-Schäden erzeugen. Mehr Abstand und Abschirmung senken die Dosis im Modell und erhöhen das Zellüberleben.",
    respiration: "In den Mitochondrien wird Glucose stufenweise oxidiert. Sauerstoff nimmt Elektronen auf; die dabei freiwerdende Energie baut ATP auf.",
    population: "Mit zunehmender Individuenzahl werden Nahrung und Raum knapp. Dadurch sinkt die Wachstumsrate und die Population nähert sich der Umweltkapazität.",
  };
  let selected; let values = {}; let time = 0; let running = false; let history = []; let radiationType = "gamma";
  const box = (label, value, unit) => `<div class="measurement"><span>${label}</span><b>${Number(value).toFixed(2)} <small>${unit}</small></b></div>`;
  function input(control) { const [key, label, min, max, value, unit] = control; return `<label class="parameter"><span>${label}<b id="bio-${key}">${value} ${unit}</b></span><input data-bio="${key}" type="range" min="${min}" max="${max}" value="${value}" step="${(max - min) / 100}" /></label>`; }
  function open(id) { selected = experiments[id]; values = Object.fromEntries(selected.controls.map(([key,,,,value]) => [key, value])); values.strahlung = radiationType; time = 0; history = []; running = false; $("#biologyEmpty").hidden = true; $("#biologyPanel").hidden = false; $("#bioRadiationTypes").hidden = id !== "radiation"; $("#bioCategory").textContent = selected.category; $("#bioTitle").textContent = selected.title; $("#bioDescription").textContent = selected.description; $("#bioExplanation").textContent = explanations[id]; $("#bioChallenge").textContent = selected.challenge; $("#bioControls").innerHTML = selected.controls.map(input).join(""); document.querySelectorAll("[data-bio-id]").forEach((card) => card.classList.toggle("active", card.dataset.bioId === id)); document.querySelectorAll("[data-bio]").forEach((element) => element.addEventListener("input", () => { values[element.dataset.bio] = Number(element.value); const definition = selected.controls.find(([key]) => key === element.dataset.bio); $(`#bio-${element.dataset.bio}`).textContent = `${Number(element.value).toFixed(definition[4] % 1 ? 2 : 0)} ${definition[5]}`; window.biology3d?.update(values); render(); })); window.biology3d?.select(id, values); render(); }
  function model() { const progress = Math.min(1, time / 10); if (selected.id === "photosynthesis") { const thermal = Math.exp(-((values.temperatur - 25) ** 2) / 180); const rate = values.licht / 100 * values.co2 / (values.co2 + 250) * thermal; return { rate, oxygen: rate * progress * 18, main: rate }; } if (selected.id === "enzymes") { const activity = Math.exp(-((values.temperatur - 37) ** 2) / 170) * Math.exp(-((values.ph - 7) ** 2) / 3) * values.substrat / (values.substrat + .5); return { activity, product: activity * progress * values.substrat, main: activity }; } if (selected.id === "osmosis") { const difference = values.aussen - values.innen; const volume = Math.max(10, Math.min(115, values.volumen - difference * progress * 28)); return { difference, volume, main: volume }; } if (selected.id === "radiation") { const properties = { alpha: [.7, 1.2], beta: [.9, .55], gamma: [1.35, .18], xray: [1.1, .28] }; const [quality, shieldingFactor] = properties[radiationType]; const doseRate = values.dosis * quality * Math.exp(-values.abschirmung * shieldingFactor) * (60 / values.abstand) ** 2; const dose = doseRate * time / 60; const survival = Math.exp(-dose * .45); return { doseRate, dose, survival, damage: (1 - survival) * 100, main: survival }; } if (selected.id === "respiration") { const thermal = Math.exp(-((values.temperatur - 37) ** 2) / 150); const rate = values.glucose * values.sauerstoff / (values.sauerstoff + 4) * thermal; return { rate, atp: rate * progress * 30, co2: rate * progress * 6, main: rate }; } const population = values.kapazitaet / (1 + ((values.kapazitaet - values.start) / values.start) * Math.exp(-values.rate * time)); return { population, main: population }; }
  function circle(x, y, radius, color) { context.fillStyle = color; context.beginPath(); context.arc(x, y, radius, 0, Math.PI * 2); context.fill(); }
  function status() { context.fillStyle = running ? "#b9d983" : "#c9d5d2"; context.font = "14px Space Grotesk"; context.fillText(running ? `Prozess läuft · ${time.toFixed(1)} s` : "Bereit · Start drücken", 24, 32); }
  function render() { if (!selected) return; const result = model(); context.clearRect(0, 0, 760, 420); context.fillStyle = "#0d2227"; context.fillRect(0, 0, 760, 420); status(); let readings = [];
    if (selected.id === "photosynthesis") { context.fillStyle = "#365b36"; context.fillRect(0, 340, 760, 80); circle(385, 220, 100, "#5d8b3c"); for (let i = 0; i < 14; i += 1) circle(335 + (i * 41 % 100), 165 + (i * 53 % 110), 15, "#87b85c"); circle(635, 90, 32, "#f4be46"); for (let i = 0; i < Math.floor(4 + result.oxygen); i += 1) circle(335 + (i * 37 % 105), 285 - ((time * 22 + i * 38) % 125), 5, "#dfeee7"); readings = [box("Photosyntheserate", result.rate * 100, "%"), box("Sauerstoff", result.oxygen, "rel."), box("Licht", values.licht, "%")]; }
    else if (selected.id === "enzymes") { circle(380, 210, 85, "#5d8b3c"); context.fillStyle = "#0d2227"; context.beginPath(); context.arc(380, 220, 28, 0, Math.PI * 2); context.fill(); for (let i = 0; i < 11; i += 1) { const x = 130 + ((i * 89 + time * 50) % 500); circle(x, 110 + (i * 61 % 210), 9, i % 2 ? "#f4be46" : "#63d6ce"); } readings = [box("Enzymaktivität", result.activity * 100, "%"), box("Produkt", result.product, "mmol/L"), box("Optimum", 37, "°C")]; }
    else if (selected.id === "osmosis") { const radius = result.volume * 1.25; context.strokeStyle = "#dfeee7"; context.lineWidth = 4; context.beginPath(); context.arc(380, 215, radius, 0, Math.PI * 2); context.stroke(); for (let i = 0; i < 20; i += 1) { const angle = i * Math.PI * 2 / 20 + time; circle(380 + Math.cos(angle) * (radius + 35), 215 + Math.sin(angle) * (radius + 35), 4, "#63d6ce"); } context.fillStyle = "#dfeee7"; context.fillText(result.difference > 0 ? "Wasser verlässt die Zelle" : "Wasser tritt in die Zelle", 280, 370); readings = [box("Zellvolumen", result.volume, "%"), box("Konzentrationsdifferenz", result.difference, "mol/L"), box("Richtung", result.difference > 0 ? 1 : -1, "")]; }
    else if (selected.id === "radiation") { context.fillStyle = "#365b36"; context.fillRect(90,95,580,250); for (let i = 0; i < 36; i += 1) { const damaged = i / 36 < result.damage / 100; circle(150 + (i * 83 % 480), 135 + (i * 47 % 170), 15, damaged ? "#e76f51" : "#87b85c"); } context.strokeStyle = "#f4be46"; context.lineWidth = 4; context.beginPath(); context.moveTo(35,210); context.lineTo(115,210); context.stroke(); context.fillStyle = "#f4be46"; context.fillText(`${radiationType.toUpperCase()}-Strahlung`,30,180); readings = [box("Dosisleistung", result.doseRate, "Gy/h"), box("DNA-Schäden", result.damage, "%"), box("Zellüberleben", result.survival * 100, "%")]; }
    else if (selected.id === "respiration") { circle(380, 210, 105, "#e76f51"); for (let i = 0; i < 18; i += 1) circle(300 + (i * 47 % 160), 135 + (i * 71 % 145), 10, i % 3 ? "#f4be46" : "#dfeee7"); for (let i = 0; i < Math.floor(result.atp); i += 1) circle(160 + (i * 31 % 100), 300 - (i * 17 % 120), 5, "#63d6ce"); readings = [box("ATP", result.atp, "rel."), box("CO₂", result.co2, "rel."), box("Atmungsrate", result.rate, "rel.")]; }
    else { context.strokeStyle = "#dfeee7"; context.beginPath(); context.moveTo(80, 350); context.lineTo(700, 350); context.stroke(); const count = Math.min(75, Math.floor(result.population / 12)); for (let i = 0; i < count; i += 1) circle(100 + (i * 57 % 570), 330 - (i * 83 % 180), 5, "#b9d983"); readings = [box("Population", result.population, ""), box("Kapazität", values.kapazitaet, ""), box("Wachstumsrate", values.rate, "pro Tag")]; }
    $("#bioMeasurements").innerHTML = readings.join(""); drawGraph(result.main); }
  function drawGraph(value) { chartContext.clearRect(0, 0, 330, 150); chartContext.fillStyle = "#10262b"; chartContext.fillRect(0, 0, 330, 150); const series = [...history, value]; if (series.length < 2) return; const max = Math.max(...series.map(Math.abs), 1); chartContext.strokeStyle = "#b9d983"; chartContext.beginPath(); series.forEach((point, index) => { const x = index / (series.length - 1) * 330; const y = 135 - point / max * 115; index ? chartContext.lineTo(x, y) : chartContext.moveTo(x, y); }); chartContext.stroke(); }
  function tick(now) { const dt = Math.min(.04, (now - (tick.last || now)) / 1000); tick.last = now; if (running && selected) { time += dt; history.push(model().main); if (history.length > 100) history.shift(); render(); } requestAnimationFrame(tick); }
  function build() { const categories = ["Alle", ...new Set(definitions.map(([, , category]) => category))]; $("#biologyFilters").innerHTML = categories.map((category, index) => `<button class="filter ${index === 0 ? "active" : ""}" data-bio-filter="${category}">${category}</button>`).join(""); $("#biologyCards").innerHTML = definitions.map(([id, title, category, description]) => `<button class="experiment-card" data-bio-id="${id}" data-bio-category="${category}" type="button"><span>${category}</span><b>${title}</b><small>${description}</small></button>`).join(""); document.querySelectorAll("[data-bio-id]").forEach((card) => card.addEventListener("click", () => open(card.dataset.bioId))); document.querySelectorAll("[data-bio-filter]").forEach((button) => button.addEventListener("click", () => { document.querySelectorAll("[data-bio-filter]").forEach((item) => item.classList.toggle("active", item === button)); filter(button.dataset.bioFilter, $("#biologySearch").value); })); }
  function filter(category, query) { const active = category || document.querySelector("[data-bio-filter].active")?.dataset.bioFilter || "Alle"; document.querySelectorAll("[data-bio-id]").forEach((card) => { card.hidden = !(active === "Alle" || card.dataset.bioCategory === active) || !card.textContent.toLowerCase().includes(query.toLowerCase()); }); }
  window.openBiologyPlatform = () => { $("#homeScreen").hidden = true; $("#labScreen").hidden = true; $("#physicsPlatform").hidden = true; $("#chemistryPlatform").hidden = true; $("#biologyPlatform").hidden = false; if (!$("#biologyCards").children.length) build(); };
  $("#biologyHomeButton").addEventListener("click", () => { running = false; window.biology3d?.setRunning(false); $("#biologyPlatform").hidden = true; $("#homeScreen").hidden = false; }); $("#bioStart").addEventListener("click", () => { running = true; window.biology3d?.setRunning(true); }); $("#bioPause").addEventListener("click", () => { running = false; window.biology3d?.setRunning(false); }); $("#bioReset").addEventListener("click", () => open(selected.id)); document.querySelectorAll("[data-radiation-type]").forEach((button) => button.addEventListener("click", () => { radiationType = button.dataset.radiationType; values.strahlung = radiationType; document.querySelectorAll("[data-radiation-type]").forEach((item) => item.classList.toggle("active", item === button)); window.biology3d?.select(selected.id, values); render(); })); $("#bioTwoDimensional").addEventListener("click", () => { $("#biologyCanvas").hidden = false; $("#biologyThreeViewport").hidden = true; $("#bioTwoDimensional").classList.add("active"); $("#bioThreeDimensional").classList.remove("active"); }); $("#bioThreeDimensional").addEventListener("click", () => { $("#biologyCanvas").hidden = true; $("#biologyThreeViewport").hidden = false; $("#bioTwoDimensional").classList.remove("active"); $("#bioThreeDimensional").classList.add("active"); window.biology3d?.select(selected.id, values); }); $("#biologySearch").addEventListener("input", (event) => filter("", event.target.value)); requestAnimationFrame(tick);
})();
